import { NextRequest, NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import { getAuthenticatedUser } from "@/lib/api-auth";

export async function GET(request: NextRequest) {
  const { user, supabase } = await getAuthenticatedUser(request);
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const teamId = request.nextUrl.searchParams.get("team_id");
  if (!teamId) {
    return NextResponse.json({ error: "team_id is required" }, { status: 400 });
  }

  const { data: team } = await supabase
    .from("teams")
    .select("*")
    .eq("id", teamId)
    .single();

  if (!team) {
    return NextResponse.json({ error: "Team not found" }, { status: 404 });
  }

  const { data: membership } = await supabase
    .from("team_members")
    .select("user_id")
    .eq("team_id", teamId)
    .eq("user_id", user.id)
    .maybeSingle();

  if (!membership && team.leader_id !== user.id) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const { data: members } = await supabase
    .from("team_members")
    .select("user_id, joined_at")
    .eq("team_id", teamId);

  const memberIds = (members ?? []).map((m) => m.user_id);
  const { data: profiles } = await supabase
    .from("profiles")
    .select("id, name, roll_no, branch, year, kiet_email")
    .in("id", memberIds.length ? memberIds : ["00000000-0000-0000-0000-000000000000"]);

  const { data: userSkills } = await supabase.from("user_skills").select("user_id, skill_id");
  const { data: skills } = await supabase.from("skills").select("id, name");

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text("KIET GROUP OF INSTITUTIONS", margin, y);
  y += 16;
  doc.setTextColor(249, 115, 22);
  doc.text("SMART INDIA HACKATHON 2026 — INTERNAL NOMINATION CARD", margin, y);
  y += 28;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(20);
  doc.text(String(team.name).toUpperCase(), margin, y);
  y += 22;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Track: ${team.problem_statement_domain}`, margin, y);
  y += 14;
  doc.text(`Status: ${team.status} • Members: ${memberIds.length}/${team.capacity}`, margin, y);
  y += 28;

  doc.setFont("helvetica", "bold");
  doc.text("Problem Statement", margin, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  const psLines = doc.splitTextToSize(String(team.problem_statement_title), 500);
  doc.text(psLines, margin, y);
  y += psLines.length * 14 + 20;

  doc.setFont("helvetica", "bold");
  doc.text("Team Roster", margin, y);
  y += 18;

  (profiles ?? []).forEach((member, index) => {
    const skillNames = (userSkills ?? [])
      .filter((us) => us.user_id === member.id)
      .map((us) => skills?.find((s) => s.id === us.skill_id)?.name)
      .filter(Boolean)
      .join(", ");

    if (y > 760) {
      doc.addPage();
      y = margin;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(`${index + 1}. ${member.name || "TBA"}`, margin, y);
    y += 14;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Roll: ${member.roll_no || "N/A"} • ${member.branch || "Branch N/A"} • Year ${member.year || "-"}`, margin, y);
    y += 12;
    doc.text(`Email: ${member.kiet_email}`, margin, y);
    y += 12;
    doc.text(`Skills: ${skillNames || "None listed"}`, margin, y);
    y += 20;
  });

  y += 10;
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text("Auto-generated by KIET SIH Team Finder Portal. For official use only.", margin, 820);

  const pdfBytes = doc.output("arraybuffer");
  const safeName = String(team.name).replace(/[^a-z0-9-_]+/gi, "_");

  return new NextResponse(pdfBytes, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${safeName}_nomination.pdf"`,
      "Cache-Control": "no-store",
    },
  });
}

export const dynamic = "force-dynamic";
